server:
  port: 8080

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/test_db_xst?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    platfrom: mysql


  application:
    name: solr
  data:
    solr:
      url: http://127.0.0.1:8983/solr/nutch
  server:
    port: 8983

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    content-type: text/html
    prefix: classpath:/template/